# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: openfortivpn-gui

builds:
  - id: gui
    main: ./cmd/openfortivpn-gui
    binary: openfortivpn-gui
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X github.com/shini4i/openfortivpn-gui/internal/ui.Version={{.Version}}

  - id: helper
    main: ./cmd/openfortivpn-gui-helper
    binary: openfortivpn-gui-helper
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

nfpms:
  - id: rpm
    formats: [rpm]
    package_name: openfortivpn-gui
    vendor: shini4i
    maintainer: shini4i
    description: GTK4/libadwaita GUI for Fortinet SSL VPN
    license: GPL-3.0
    dependencies:
      - gtk4
      - libadwaita
      - libsecret
      - openfortivpn
    contents:
      - src: ./data/com.github.shini4i.openfortivpn-gui.desktop
        dst: /usr/share/applications/com.github.shini4i.openfortivpn-gui.desktop
        file_info:
          mode: 0644
      - src: ./data/openfortivpn-gui-helper.service
        dst: /usr/lib/systemd/system/openfortivpn-gui-helper.service
        file_info:
          mode: 0644
    scripts:
      postinstall: ./packaging/scripts/postinstall.sh
      preremove: ./packaging/scripts/preremove.sh

changelog:
  use: github-native

release:
  github:
    owner: shini4i
    name: openfortivpn-gui
